/* ===================================================================
   Framer Offline Service Worker — auto-generated by framer_extractor
   Intercepts CDN requests and serves locally-downloaded assets.
   Version: 1777453987  ← timestamp changes every extraction,
            so the browser always installs this new SW and discards
            any stale cached version from a previous run.
   =================================================================== */

const CDN_MAP      = {
  "https://fonts.gstatic.com/s/hankengrotesk/v12/ieVn2YZDLWuGJpnzaiwFXS9tYtpQ59CjCQ.woff2": "/assets/fonts.gstatic.com/s/hankengrotesk/v12/ieVn2YZDLWuGJpnzaiwFXS9tYtpQ59CjCQ.woff2",
  "https://fonts.gstatic.com/s/hankengrotesk/v12/ieVn2YZDLWuGJpnzaiwFXS9tYtpS59CjCQ.woff2": "/assets/fonts.gstatic.com/s/hankengrotesk/v12/ieVn2YZDLWuGJpnzaiwFXS9tYtpS59CjCQ.woff2",
  "https://fonts.gstatic.com/s/hankengrotesk/v12/ieVn2YZDLWuGJpnzaiwFXS9tYtpT59CjCQ.woff2": "/assets/fonts.gstatic.com/s/hankengrotesk/v12/ieVn2YZDLWuGJpnzaiwFXS9tYtpT59CjCQ.woff2",
  "https://fonts.gstatic.com/s/hankengrotesk/v12/ieVn2YZDLWuGJpnzaiwFXS9tYtpd59A.woff2": "/assets/fonts.gstatic.com/s/hankengrotesk/v12/ieVn2YZDLWuGJpnzaiwFXS9tYtpd59A.woff2",
  "https://fonts.gstatic.com/s/hankengrotesk/v12/ieVq2YZDLWuGJpnzaiwFXS9tYvBRzyFLlZg_f_NcVGFa5PpNzXhRKA.woff2": "/assets/fonts.gstatic.com/s/hankengrotesk/v12/ieVq2YZDLWuGJpnzaiwFXS9tYvBRzyFLlZg_f_NcVGFa5PpNzXhRKA.woff2",
  "https://fonts.gstatic.com/s/hankengrotesk/v12/ieVq2YZDLWuGJpnzaiwFXS9tYvBRzyFLlZg_f_Ncs2Za5PpNzXhRKA.woff2": "/assets/fonts.gstatic.com/s/hankengrotesk/v12/ieVq2YZDLWuGJpnzaiwFXS9tYvBRzyFLlZg_f_Ncs2Za5PpNzXhRKA.woff2",
  "https://framer.com/m/feather-icons/chevron-right.js@0.0.29": "/assets/framer.com/m/feather-icons/chevron-right.js@0.0.29",
  "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2": "/assets/framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
  "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2": "/assets/framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
  "https://framerusercontent.com/assets/3dpALmvrIR88qPmbDlYoTyJSig.png": "/assets/framerusercontent.com/assets/3dpALmvrIR88qPmbDlYoTyJSig.png",
  "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2": "/assets/framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
  "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2": "/assets/framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
  "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2": "/assets/framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
  "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2": "/assets/framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
  "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2": "/assets/framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
  "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2": "/assets/framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
  "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2": "/assets/framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
  "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2": "/assets/framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
  "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2": "/assets/framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
  "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2": "/assets/framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
  "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2": "/assets/framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
  "https://framerusercontent.com/assets/HDdSBGm2zGGVIOY2E0WY2YlVU.ttf": "/assets/framerusercontent.com/assets/HDdSBGm2zGGVIOY2E0WY2YlVU.ttf",
  "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2": "/assets/framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
  "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2": "/assets/framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
  "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2": "/assets/framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
  "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2": "/assets/framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
  "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2": "/assets/framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
  "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2": "/assets/framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
  "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2": "/assets/framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
  "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2": "/assets/framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
  "https://framerusercontent.com/assets/iHc6cFFuF5Ba9NQr3a7tjB8jE.jpg": "/assets/framerusercontent.com/assets/iHc6cFFuF5Ba9NQr3a7tjB8jE.jpg",
  "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2": "/assets/framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
  "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2": "/assets/framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
  "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2": "/assets/framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
  "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2": "/assets/framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
  "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2": "/assets/framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
  "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2": "/assets/framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
  "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2": "/assets/framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
  "https://framerusercontent.com/images/3dpALmvrIR88qPmbDlYoTyJSig.png": "/assets/framerusercontent.com/images/3dpALmvrIR88qPmbDlYoTyJSig.png",
  "https://framerusercontent.com/images/3dpALmvrIR88qPmbDlYoTyJSig.png?width=328&height=322": "/assets/framerusercontent.com/images/3dpALmvrIR88qPmbDlYoTyJSig_cd15f5.png",
  "https://framerusercontent.com/images/3dpALmvrIR88qPmbDlYoTyJSig_cd15f5.png": "/assets/framerusercontent.com/images/3dpALmvrIR88qPmbDlYoTyJSig_cd15f5.png",
  "https://framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo.png": "/assets/framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo.png",
  "https://framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo.png?scale-down-to=1024&width=1254&height=1254": "/assets/framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo_9363ed.png",
  "https://framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo.png?scale-down-to=512&width=1254&height=1254": "/assets/framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo_8e60bf.png",
  "https://framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo.png?width=1254&height=1254": "/assets/framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo_08fae8.png",
  "https://framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo_08fae8.png": "/assets/framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo_08fae8.png",
  "https://framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo_8e60bf.png": "/assets/framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo_8e60bf.png",
  "https://framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo_9363ed.png": "/assets/framerusercontent.com/images/7Z1UfRCqkqmc5zB4X1Xiy3H7nmo_9363ed.png",
  "https://framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU.jpg": "/assets/framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU.jpg",
  "https://framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU.jpg?scale-down-to=1024&width=6000&height=4000": "/assets/framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_43dd66.jpg",
  "https://framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU.jpg?scale-down-to=2048&width=6000&height=4000": "/assets/framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_0de854.jpg",
  "https://framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU.jpg?scale-down-to=4096&width=6000&height=4000": "/assets/framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_3b944a.jpg",
  "https://framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU.jpg?scale-down-to=512&width=6000&height=4000": "/assets/framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_d3497e.jpg",
  "https://framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU.jpg?width=6000&height=4000": "/assets/framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_97d1e1.jpg",
  "https://framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_0de854.jpg": "/assets/framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_0de854.jpg",
  "https://framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_3b944a.jpg": "/assets/framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_3b944a.jpg",
  "https://framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_43dd66.jpg": "/assets/framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_43dd66.jpg",
  "https://framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_97d1e1.jpg": "/assets/framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_97d1e1.jpg",
  "https://framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_d3497e.jpg": "/assets/framerusercontent.com/images/82V0lDZt5IN8w9i1157kfT8pSU_d3497e.jpg",
  "https://framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg.jpg": "/assets/framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg.jpg",
  "https://framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg.jpg?scale-down-to=1024&width=10000&height=6667": "/assets/framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_58dfff.jpg",
  "https://framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg.jpg?scale-down-to=2048&width=10000&height=6667": "/assets/framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_3c700c.jpg",
  "https://framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg.jpg?scale-down-to=4096&width=10000&height=6667": "/assets/framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_b5a28a.jpg",
  "https://framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg.jpg?scale-down-to=512&width=10000&height=6667": "/assets/framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_4e6534.jpg",
  "https://framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg.jpg?width=10000&height=6667": "/assets/framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_9351cc.jpg",
  "https://framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_3c700c.jpg": "/assets/framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_3c700c.jpg",
  "https://framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_4e6534.jpg": "/assets/framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_4e6534.jpg",
  "https://framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_58dfff.jpg": "/assets/framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_58dfff.jpg",
  "https://framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_9351cc.jpg": "/assets/framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_9351cc.jpg",
  "https://framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_b5a28a.jpg": "/assets/framerusercontent.com/images/8ZlsEfjDITR5nOu3Yn61F22cbg_b5a28a.jpg",
  "https://framerusercontent.com/images/Jt3ctw2OTgLUHh7MdFLeLhyxAk.png": "/assets/framerusercontent.com/images/Jt3ctw2OTgLUHh7MdFLeLhyxAk.png",
  "https://framerusercontent.com/images/Jt3ctw2OTgLUHh7MdFLeLhyxAk.png?width=342&height=99": "/assets/framerusercontent.com/images/Jt3ctw2OTgLUHh7MdFLeLhyxAk_79f6c4.png",
  "https://framerusercontent.com/images/Jt3ctw2OTgLUHh7MdFLeLhyxAk_79f6c4.png": "/assets/framerusercontent.com/images/Jt3ctw2OTgLUHh7MdFLeLhyxAk_79f6c4.png",
  "https://framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE.jpg": "/assets/framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_22560d.jpg",
  "https://framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE.jpg?scale-down-to=1024&width=3840&height=2160": "/assets/framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_22560d.jpg",
  "https://framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE.jpg?scale-down-to=2048&width=3840&height=2160": "/assets/framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_a34843.jpg",
  "https://framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE.jpg?scale-down-to=512&width=3840&height=2160": "/assets/framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_e975e1.jpg",
  "https://framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE.jpg?width=3840&height=2160": "/assets/framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_cd0170.jpg",
  "https://framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_22560d.jpg": "/assets/framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_22560d.jpg",
  "https://framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_a34843.jpg": "/assets/framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_a34843.jpg",
  "https://framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_cd0170.jpg": "/assets/framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_cd0170.jpg",
  "https://framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_e975e1.jpg": "/assets/framerusercontent.com/images/KHgIfpCUTM3SEAMCBkivLyl9oE_e975e1.jpg",
  "https://framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig.jpg": "/assets/framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig.jpg",
  "https://framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig.jpg?scale-down-to=1024&width=3840&height=2160": "/assets/framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig_22560d.jpg",
  "https://framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig.jpg?scale-down-to=2048&width=3840&height=2160": "/assets/framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig_a34843.jpg",
  "https://framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig.jpg?scale-down-to=512&width=3840&height=2160": "/assets/framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig_e975e1.jpg",
  "https://framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig.jpg?width=3840&height=2160": "/assets/framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig_cd0170.jpg",
  "https://framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig_22560d.jpg": "/assets/framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig_22560d.jpg",
  "https://framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig_a34843.jpg": "/assets/framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig_a34843.jpg",
  "https://framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig_cd0170.jpg": "/assets/framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig_cd0170.jpg",
  "https://framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig_e975e1.jpg": "/assets/framerusercontent.com/images/UlzZi7Dd7txMrOquJLbf9wyEiig_e975e1.jpg",
  "https://framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw.png": "/assets/framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw.png",
  "https://framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw.png?scale-down-to=1024&width=1672&height=941": "/assets/framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw_691588.png",
  "https://framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw.png?scale-down-to=512&width=1672&height=941": "/assets/framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw_b9fcd0.png",
  "https://framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw.png?width=1672&height=941": "/assets/framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw_40a72d.png",
  "https://framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw_40a72d.png": "/assets/framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw_40a72d.png",
  "https://framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw_691588.png": "/assets/framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw_691588.png",
  "https://framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw_b9fcd0.png": "/assets/framerusercontent.com/images/VCeBzpnD1XGEdfm6FfSacwZLXw_b9fcd0.png",
  "https://framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU.jpg": "/assets/framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU.jpg",
  "https://framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU.jpg?scale-down-to=1024&width=6000&height=4558": "/assets/framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_3a65bc.jpg",
  "https://framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU.jpg?scale-down-to=2048&width=6000&height=4558": "/assets/framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_6ad147.jpg",
  "https://framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU.jpg?scale-down-to=4096&width=6000&height=4558": "/assets/framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_62938e.jpg",
  "https://framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU.jpg?scale-down-to=512&width=6000&height=4558": "/assets/framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_a26300.jpg",
  "https://framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU.jpg?width=6000&height=4558": "/assets/framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_104f0f.jpg",
  "https://framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_104f0f.jpg": "/assets/framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_104f0f.jpg",
  "https://framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_3a65bc.jpg": "/assets/framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_3a65bc.jpg",
  "https://framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_62938e.jpg": "/assets/framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_62938e.jpg",
  "https://framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_6ad147.jpg": "/assets/framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_6ad147.jpg",
  "https://framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_a26300.jpg": "/assets/framerusercontent.com/images/Y1hHthCTPz6YNLIhonp2E5s5WU_a26300.jpg",
  "https://framerusercontent.com/images/amPU084wt55zk7DxOzOrzfEvhI.png": "/assets/framerusercontent.com/images/amPU084wt55zk7DxOzOrzfEvhI.png",
  "https://framerusercontent.com/images/amPU084wt55zk7DxOzOrzfEvhI.png?width=48&height=48": "/assets/framerusercontent.com/images/amPU084wt55zk7DxOzOrzfEvhI_e185ff.png",
  "https://framerusercontent.com/images/amPU084wt55zk7DxOzOrzfEvhI_e185ff.png": "/assets/framerusercontent.com/images/amPU084wt55zk7DxOzOrzfEvhI_e185ff.png",
  "https://framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc.png": "/assets/framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc.png",
  "https://framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc.png?scale-down-to=1024&width=1254&height=1254": "/assets/framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc_9363ed.png",
  "https://framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc.png?scale-down-to=512&width=1254&height=1254": "/assets/framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc_8e60bf.png",
  "https://framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc.png?width=1254&height=1254": "/assets/framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc_08fae8.png",
  "https://framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc_08fae8.png": "/assets/framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc_08fae8.png",
  "https://framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc_8e60bf.png": "/assets/framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc_8e60bf.png",
  "https://framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc_9363ed.png": "/assets/framerusercontent.com/images/b8foXBTBgt1cg8eg2XaHtHc_9363ed.png",
  "https://framerusercontent.com/images/iHc6cFFuF5Ba9NQr3a7tjB8jE.jpg": "/assets/framerusercontent.com/images/iHc6cFFuF5Ba9NQr3a7tjB8jE.jpg",
  "https://framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY.png": "/assets/framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY.png",
  "https://framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY.png?scale-down-to=1024&width=1672&height=941": "/assets/framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY_691588.png",
  "https://framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY.png?scale-down-to=512&width=1672&height=941": "/assets/framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY_b9fcd0.png",
  "https://framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY.png?width=1672&height=941": "/assets/framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY_40a72d.png",
  "https://framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY_40a72d.png": "/assets/framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY_40a72d.png",
  "https://framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY_691588.png": "/assets/framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY_691588.png",
  "https://framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY_b9fcd0.png": "/assets/framerusercontent.com/images/mJ5n0dMtri24L6CpVnXxWLmuMwY_b9fcd0.png",
  "https://framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4.png": "/assets/framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4.png",
  "https://framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4.png?scale-down-to=1024&width=1254&height=1254": "/assets/framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4_9363ed.png",
  "https://framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4.png?scale-down-to=512&width=1254&height=1254": "/assets/framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4_8e60bf.png",
  "https://framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4.png?width=1254&height=1254": "/assets/framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4_08fae8.png",
  "https://framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4_08fae8.png": "/assets/framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4_08fae8.png",
  "https://framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4_8e60bf.png": "/assets/framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4_8e60bf.png",
  "https://framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4_9363ed.png": "/assets/framerusercontent.com/images/mkbDeJZqo3Wd4iulEgnyMJwq1W4_9363ed.png",
  "https://framerusercontent.com/images/qIVyMWLgN7AUAf2v9j5mSFmDB8.png": "/assets/framerusercontent.com/images/qIVyMWLgN7AUAf2v9j5mSFmDB8.png",
  "https://framerusercontent.com/images/qIVyMWLgN7AUAf2v9j5mSFmDB8.png?width=48&height=48": "/assets/framerusercontent.com/images/qIVyMWLgN7AUAf2v9j5mSFmDB8_e185ff.png",
  "https://framerusercontent.com/images/qIVyMWLgN7AUAf2v9j5mSFmDB8_e185ff.png": "/assets/framerusercontent.com/images/qIVyMWLgN7AUAf2v9j5mSFmDB8_e185ff.png",
  "https://framerusercontent.com/images/qwT3OVS60T2GFXI6UzkjBgV4M.png": "/assets/framerusercontent.com/images/qwT3OVS60T2GFXI6UzkjBgV4M.png",
  "https://framerusercontent.com/images/qwT3OVS60T2GFXI6UzkjBgV4M.png?scale-down-to=512&width=1024&height=1024": "/assets/framerusercontent.com/images/qwT3OVS60T2GFXI6UzkjBgV4M_9adb09.png",
  "https://framerusercontent.com/images/qwT3OVS60T2GFXI6UzkjBgV4M.png?width=1024&height=1024": "/assets/framerusercontent.com/images/qwT3OVS60T2GFXI6UzkjBgV4M_90eed7.png",
  "https://framerusercontent.com/images/qwT3OVS60T2GFXI6UzkjBgV4M_90eed7.png": "/assets/framerusercontent.com/images/qwT3OVS60T2GFXI6UzkjBgV4M_90eed7.png",
  "https://framerusercontent.com/images/qwT3OVS60T2GFXI6UzkjBgV4M_9adb09.png": "/assets/framerusercontent.com/images/qwT3OVS60T2GFXI6UzkjBgV4M_9adb09.png",
  "https://framerusercontent.com/images/rR6HYXBrMmX4cRpXfXUOvpvpB0.png": "/assets/framerusercontent.com/images/rR6HYXBrMmX4cRpXfXUOvpvpB0.png",
  "https://framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE.png": "/assets/framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE.png",
  "https://framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE.png?scale-down-to=1024&width=1254&height=1254": "/assets/framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE_9363ed.png",
  "https://framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE.png?scale-down-to=512&width=1254&height=1254": "/assets/framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE_8e60bf.png",
  "https://framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE.png?width=1254&height=1254": "/assets/framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE_08fae8.png",
  "https://framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE_08fae8.png": "/assets/framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE_08fae8.png",
  "https://framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE_8e60bf.png": "/assets/framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE_8e60bf.png",
  "https://framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE_9363ed.png": "/assets/framerusercontent.com/images/xnmy5u8pIkBooJ2ygyaE7oZDgmE_9363ed.png",
  "https://framerusercontent.com/modules/9r7U0ve666zqgz7BLHoX/AFcAYpWXQtry97djAUwo/chevron-right.js": "/assets/framerusercontent.com/modules/9r7U0ve666zqgz7BLHoX/AFcAYpWXQtry97djAUwo/chevron-right.js",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/3BTLanB2I1bG5pwqMH7iNSJrK-Xlp-Xl6c1kOaaaIhs.WLFf2BFo.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/3BTLanB2I1bG5pwqMH7iNSJrK-Xlp-Xl6c1kOaaaIhs.WLFf2BFo.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/CqBKBtR7I.BgZzpAnX.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/CqBKBtR7I.BgZzpAnX.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/JDfmSEp1m.BvwU9aOy.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/JDfmSEp1m.BvwU9aOy.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/NhXtZlRoQYTca00FwHEHWSjrP5AriupMIqqrqFlnqOM.CHgm-HrV.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/NhXtZlRoQYTca00FwHEHWSjrP5AriupMIqqrqFlnqOM.CHgm-HrV.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/PNPloaqercCtIWIMyx33M4JbBF0ed90RDvrELSuSdP8.Bv763zaK.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/PNPloaqercCtIWIMyx33M4JbBF0ed90RDvrELSuSdP8.Bv763zaK.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/PX9hIOIVM.bgMr7HtN.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/PX9hIOIVM.bgMr7HtN.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/QCtzoRG1E.D_8y6JoS.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/QCtzoRG1E.D_8y6JoS.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/TDg16Y5Jj.ChvFeHWg.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/TDg16Y5Jj.ChvFeHWg.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/VN5rnreIpuuH2Iv4MgygUv3fRtQWy_x9R5_Ztb_bZQE.CoIMQl7S.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/VN5rnreIpuuH2Iv4MgygUv3fRtQWy_x9R5_Ztb_bZQE.CoIMQl7S.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/alx4fZ_Ki_OjWY3m8vSUvYuF5p99aecgioHy5mc-cGQ.TZ9cZeQk.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/alx4fZ_Ki_OjWY3m8vSUvYuF5p99aecgioHy5mc-cGQ.TZ9cZeQk.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/eddhjzMea.BE4dxVyu.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/eddhjzMea.BE4dxVyu.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/fontshare-LTYJMI6Q.Cr1usED2.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/fontshare-LTYJMI6Q.Cr1usED2.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/fontshare-X63NXWGB.U5952x9t.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/fontshare-X63NXWGB.U5952x9t.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/fontshare-XMKN2FOD.DwyuHx4F.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/fontshare-XMKN2FOD.DwyuHx4F.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/framer-font-D6RMCRV4.BmjD442o.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/framer-font-D6RMCRV4.BmjD442o.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/framer.C9iHScM4.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/framer.C9iHScM4.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/google-5NZOMG37.DiUlDbcT.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/google-5NZOMG37.DiUlDbcT.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/google-BHSMRPXK.C3TDYQvD.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/google-BHSMRPXK.C3TDYQvD.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/google-OGWBHVGI.D1kQzr5Z.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/google-OGWBHVGI.D1kQzr5Z.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/mPLIoTYJu.ChMgxSWG.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/mPLIoTYJu.ChMgxSWG.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/motion.DwahgEmI.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/motion.DwahgEmI.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/o8skT4YNp.BT2FxzW0.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/o8skT4YNp.BT2FxzW0.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/pxEHKEms8.DJxpucD1.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/pxEHKEms8.DJxpucD1.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/react.DOXjZN3b.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/react.DOXjZN3b.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/rolldown-runtime.B6Nc_XXV.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/rolldown-runtime.B6Nc_XXV.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/s8RouUFOSS3zQxPb7eGEeG1eAiXM7Ir0T31YlEmJX6c.DVE4CIOY.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/s8RouUFOSS3zQxPb7eGEeG1eAiXM7Ir0T31YlEmJX6c.DVE4CIOY.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/script_main.CQqV4DrM.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/script_main.CQqV4DrM.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/searchIndex-VEyLkQKDthJ3.json": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/searchIndex-VEyLkQKDthJ3.json",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/searchIndex-j56iITrROLUG.json": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/searchIndex-j56iITrROLUG.json",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/shared-lib.CsuTgE1i.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/shared-lib.CsuTgE1i.mjs",
  "https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/vDltKVZ8B.BPPF0THh.mjs": "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/vDltKVZ8B.BPPF0THh.mjs",
  "https://framerusercontent.com/third-party-assets/fontshare/": "/assets/framerusercontent.com/third-party-assets/fontshare/index.html",
  "https://framerusercontent.com/third-party-assets/fontshare/index.html": "/assets/framerusercontent.com/third-party-assets/fontshare/index.html",
  "https://framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2": "/assets/framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2",
  "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2": "/assets/framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
  "https://framerusercontent.com/third-party-assets/fontshare/wf/MPIFA4B3XXRNY2MJDGP6GOOOAF6EOCLO/W5E4ZFYPJ3V6JKMBGHB6YMITK6EWS2XA/QOMBWPST76ICDYF6WOBS7SQ7RBT67QW2.woff2": "/assets/framerusercontent.com/third-party-assets/fontshare/wf/MPIFA4B3XXRNY2MJDGP6GOOOAF6EOCLO/W5E4ZFYPJ3V6JKMBGHB6YMITK6EWS2XA/QOMBWPST76ICDYF6WOBS7SQ7RBT67QW2.woff2",
  "https://framerusercontent.com/third-party-assets/fontshare/wf/NID3I7RITWZSKXRCJGOCMP5NOADJK6IG/2HLHGD7OBTWCOHW64YXOE5KFXHU4KJHM/ZHME2QIRFR7UPJ47NLY27RCAFY44CKZJ.woff2": "/assets/framerusercontent.com/third-party-assets/fontshare/wf/NID3I7RITWZSKXRCJGOCMP5NOADJK6IG/2HLHGD7OBTWCOHW64YXOE5KFXHU4KJHM/ZHME2QIRFR7UPJ47NLY27RCAFY44CKZJ.woff2",
  "https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2": "/assets/framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
  "https://framerusercontent.com/third-party-assets/fontshare/wf/TTX2Z3BF3P6Y5BQT3IV2VNOK6FL22KUT/7QYRJOI3JIMYHGY6CH7SOIFRQLZOLNJ6/KFIAZD4RUMEZIYV6FQ3T3GP5PDBDB6JY.woff2": "/assets/framerusercontent.com/third-party-assets/fontshare/wf/TTX2Z3BF3P6Y5BQT3IV2VNOK6FL22KUT/7QYRJOI3JIMYHGY6CH7SOIFRQLZOLNJ6/KFIAZD4RUMEZIYV6FQ3T3GP5PDBDB6JY.woff2",
  "https://tidy-beginning-967967.framer.app/": "/index.html",
  "https://tidy-beginning-967967.framer.app/projects": "/projects.html",
  "https://tidy-beginning-967967.framer.app/projects/digital-wallet-ledger-engine": "/projects/digital-wallet-ledger-engine.html",
  "https://tidy-beginning-967967.framer.app/projects/hyperlocal-delivery-tracking-system": "/projects/hyperlocal-delivery-tracking-system.html",
  "https://tidy-beginning-967967.framer.app/robots.txt": "/robots.txt"
};
const CDN_BASE_MAP = [
  ["https://framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/", "/assets/framerusercontent.com/sites/4HqwIJe7yJLXXESG2SdGxI/"]
];

// skipWaiting() + clients.claim() — safe to call here because:
//
// The concern with skipWaiting() is that a SW activated mid-hydration could
// intercept React's dynamic import() calls and return unexpected bytes, causing
// a hydration mismatch (blank screen).  That risk existed when the SW was the
// ONLY mechanism serving local assets.
//
// On a Vercel/production deployment, Phases 4 and 5 already rewrote every CDN
// URL in the HTML and JS bundles to root-relative local paths (/assets/...).
// Those paths are served directly by Vercel's CDN — the SW never sees them.
// The SW on Vercel only intercepts any CDN URLs that *leaked* through the
// rewrite phases (extremely rare).  It cannot interfere with hydration because:
//   • It only matches https://framerusercontent.com/... (not /assets/...)
//   • React's import() calls post-Phase-5 use /assets/... paths
//   • So the SW intercepts nothing during hydration — it has no race to win
//
// skipWaiting() → SW activates immediately after install (no second-visit wait)
// clients.claim() → SW controls the current page from first visit onward
self.addEventListener('install', (event) => {
    event.waitUntil(self.skipWaiting());
});
self.addEventListener('activate', (event) => {
    event.waitUntil(clients.claim());
});

function _offlineResponse(url) {
    // Return a valid empty JS module for .mjs/.js so a missing chunk
    // produces a no-op instead of a SyntaxError that crashes React.
    if (/\.m?js($|[?#])/.test(url)) {
        return new Response('/* offline: chunk not found */', {
            status: 200,
            headers: { 'Content-Type': 'application/javascript' }
        });
    }
    // Bug 23 fix: return a transparent 1×1 PNG for images so broken-image
    // icons don't appear on the page when an asset can't be served offline.
    if (/\.(png|jpe?g|gif|webp|avif|svg)($|[?#])/.test(url)) {
        // Smallest valid transparent PNG (68 bytes, base64-encoded)
        const B64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==';
        const bin = atob(B64);
        const arr = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
        return new Response(arr, { status: 200, headers: { 'Content-Type': 'image/png' } });
    }
    return new Response('', { status: 404, statusText: 'Offline: asset not found' });
}

self.addEventListener('fetch', event => {
    const url = event.request.url;

    // 1) Exact match — pre-downloaded CDN asset
    const exactLocal = CDN_MAP[url];
    if (exactLocal) {
        event.respondWith(
            fetch(exactLocal).catch(() => _offlineResponse(url))
        );
        return;
    }

    // 2) Local-path intercept — Phase 5 may have rewritten CDN strings in JS
    // bundles to root-relative paths like /assets/framerusercontent.com/...
    // Those requests go to the local server directly, but if for any reason
    // the SW intercepts them first (scope overlap), we pass them through.
    if (url.includes('/assets/framerusercontent.com/')
            || url.includes('/assets/fonts.gstatic.com/')
            || url.includes('/assets/fonts.googleapis.com/')) {
        // Let the local server handle it — no respondWith means browser default.
        return;
    }

    // 3) Prefix match — dynamic chunk whose hash wasn't in cdn_map
    for (const [cdnBase, localBase] of CDN_BASE_MAP) {
        if (url.startsWith(cdnBase)) {
            const localUrl = localBase + url.slice(cdnBase.length).split('?')[0];
            event.respondWith(
                fetch(localUrl).catch(() => _offlineResponse(url))
            );
            return;
        }
    }
    // 4) Not a CDN URL — browser handles it normally (no event.respondWith)
});
